-- Canonical schema for the complaints channel.
--
-- Apply manually in Supabase SQL editor on first setup and after any change.
-- This file is the source of truth — if production drifts, reconcile here.
--
-- Security posture:
--   * Inserts come exclusively from the Next.js route handler at
--     src/app/api/complaints/route.ts, authenticated with SERVICE_ROLE_KEY.
--     SERVICE_ROLE bypasses RLS, so this table never relies on policies for
--     write protection.
--   * RLS is enabled with NO policies. Defense in depth: if the anon or
--     authenticated key is ever exposed (or if a future /admin route uses
--     the wrong client), all access is denied by default.
--   * When the /admin/complaints panel is built, add narrowly-scoped policies
--     keyed on a verified admin role/JWT claim — do NOT open this table to
--     anon or authenticated broadly.

create table if not exists public.complaints (
  id             bigint generated by default as identity primary key,
  reference_id   text        not null unique,
  reporter_class text        not null default 'external'
                 check (reporter_class in ('internal', 'external')),
  type           text        not null check (type in ('complaint', 'grievance', 'report')),
  anonymous      boolean     not null default false,
  name          text,
  email         text,
  phone         text,
  subject       text        not null,
  description   text        not null,
  locale        text        not null check (locale in ('es', 'en')),
  status        text        not null default 'open'
                check (status in ('open', 'in_progress', 'resolved', 'closed')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists complaints_created_at_idx on public.complaints (created_at desc);
create index if not exists complaints_status_idx     on public.complaints (status);
create index if not exists complaints_type_idx       on public.complaints (type);
create index if not exists complaints_reporter_class_idx on public.complaints (reporter_class);

-- MIGRATION for an existing database (run once in the Supabase SQL editor).
-- Adds the reporter_class column without breaking existing rows: they default
-- to 'external'. Safe to run repeatedly (idempotent).
--   alter table public.complaints
--     add column if not exists reporter_class text not null default 'external'
--     check (reporter_class in ('internal', 'external'));
--   create index if not exists complaints_reporter_class_idx
--     on public.complaints (reporter_class);

-- Touch updated_at on every UPDATE.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists complaints_set_updated_at on public.complaints;
create trigger complaints_set_updated_at
  before update on public.complaints
  for each row
  execute function public.set_updated_at();

-- Enforce RLS. No policies on purpose. Service role bypasses RLS.
alter table public.complaints enable row level security;

-- Optional hardening (uncomment if/when needed):
-- revoke all on public.complaints from anon, authenticated;
